[project]
name = "meraki"
version = "2.0.3"
description = "Meraki library for Python"
authors = [
    {name = "Cisco Meraki",email = "api-feedback@meraki.net"}
]
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests (>=2.32.2,<3.0.0)",
    "aiohttp (>=3.11.18,<4.0.0)",
    "jinja2 (==3.1.6)",
    "pytest (>=8.3.5,<10.0.0)"
]

[project.urls]
homepage = "https://github.com/meraki/dashboard-api-python"
repository = "https://github.com/meraki/dashboard-api-python"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0","setuptools>=78.1.1,<79.0.0"]
build-backend = "poetry.core.masonry.api"